SELECT *
FROM EMPLOYEES;

SELECT EMPLOYEE_ID,('NAME: ' ||FIRST_NAME || ' ' || LAST_NAME) "FULL NAME" , SALARY
FROM EMPLOYEES;

SELECT EMPLOYEE_ID,FIRST_NAME "NAME",(SALARY*12)*.015 "ANUAL VAT"
FROM EMPLOYEES;

SELECT FIRST_NAME|| LAST_NAME "NAME", COMMISSION_PCT
FROM EMPLOYEES;

SELECT FIRST_NAME NAME, (SALARY +SALARY *COMMISSION_PCT) "SAL-COM/NULL"
FROM EMPLOYEES;

SELECT DISTINCT JOB_ID
FROM EMPLOYEES;

DESCRIBE EMPLOYEES;

SELECT JOB_TITLE FROM JOBS;

SELECT LOCATION_ID,STREET_ADDRESS || ', ' || CITY || ', ' || STATE_PROVINCE || ',
' || POSTAL_CODE AS ADDRESS FROM LOCATIONS ;

SELECT DISTINCT DEPARTMENT_ID FROM EMPLOYEES;
SELECT SALARY, FIRST_NAME|| ' ' ||LAST_NAME AS NAME FROM EMPLOYEES WHERE DEPARTMENT_ID=80;

SELECT LAST_NAME, SALARY,HIRE_DATE AS HD
FROM EMPLOYEES
WHERE HIRE_DATE > '01-JAN-1995'
ORDER BY HD;

SELECT EMPLOYEE_ID, FIRST_NAME|| ' '|| LAST_NAME AS NAME FROM EMPLOYEES WHERE HIRE_DATE>= '01-JAN-2003' AND HIRE_DATE<= '31-DEC-2003';

SELECT LAST_NAME, SALARY
FROM EMPLOYEES
WHERE HIRE_DATE BETWEEN '01-JAN-2003' AND '31-DEC-2003' ;

SELECT EMPLOYEE_ID,DEPARTMENT_ID FROM EMPLOYEES WHERE DEPARTMENT_ID IN(50,80) OR SALARY >5000;

SELECT LAST_NAME FROM EMPLOYEES WHERE LAST_NAME LIKE '_a%' OR (LAST_NAME LIKE '_e%') OR (LAST_NAME LIKE '_i%') OR (LAST_NAME LIKE '_o%') OR (LAST_NAME LIKE '_u%');

SELECT FIRST_NAME||LAST_NAME AS NAME FROM EMPLOYEES WHERE HIRE_DATE<'01-JAN-1998';

SELECT EMPLOYEE_ID, FIRST_NAME || LAST_NAME AS NAME, SALARY, JOB_ID,COMMISSION_PCT
FROM EMPLOYEES WHERE JOB_ID LIKE 'AD_PRES' 
ORDER BY COMMISSION_PCT ASC, SALARY DESC;

SELECT (INITCAP(FIRST_NAME) || ' ' || LOWER(LAST_NAME)) NAME, UPPER(JOB_ID) JOB
FROM EMPLOYEES ;

SELECT * FROM DEPARTMENTS WHERE LOWER(DEPARTMENT_NAME) LIKE '%sale%';

SELECT CONCAT(FIRST_NAME, LAST_NAME) NAME, JOB_ID
FROM EMPLOYEES
WHERE INSTR( UPPER(JOB_ID), 'CLERK') > 0 ;

SELECT CONCAT(UPPER(SUBSTR(COUNTRY_NAME,1,3)),CONCAT(' ',UPPER(SUBSTR(COUNTRY_NAME,LENGTH(COUNTRY_NAME)-2)))) AS NEW
FROM COUNTRIES;

SELECT LAST_NAME, NVL(COMMISSION_PCT, 0) COMMISSION
FROM EMPLOYEES ;

SELECT STREET_ADDRESS, POSTAL_CODE
FROM LOCATIONS
ORDER BY POSTAL_CODE ASC ;
